package dao;
import config.Database;import model.Transfer;import java.sql.*;import java.util.*;
public class TransferDao{
 private Transfer map(ResultSet r)throws SQLException{return new Transfer(r.getInt(1),r.getInt(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),String.valueOf(r.getTimestamp(7)),r.getTimestamp(8)==null?null:String.valueOf(r.getTimestamp(8)));}
 public int create(int d,int s,int r,String h)throws SQLException{try(Connection c=Database.getConnection();PreparedStatement p=c.prepareStatement("INSERT INTO transfers(document_id,sender_id,receiver_id,handover_code_hash) VALUES(?,?,?,?)",Statement.RETURN_GENERATED_KEYS)){p.setInt(1,d);p.setInt(2,s);p.setInt(3,r);p.setString(4,h);p.executeUpdate();ResultSet x=p.getGeneratedKeys();x.next();return x.getInt(1);}}
 public String codeHash(int id)throws SQLException{try(Connection c=Database.getConnection();PreparedStatement p=c.prepareStatement("SELECT handover_code_hash FROM transfers WHERE id=?")){p.setInt(1,id);ResultSet r=p.executeQuery();return r.next()?r.getString(1):null;}}
 public Transfer pending(int id,int receiver)throws SQLException{String q="SELECT t.id,t.document_id,d.original_name,s.name,r.name,t.status,t.created_at,t.received_at FROM transfers t JOIN documents d ON t.document_id=d.id JOIN users s ON t.sender_id=s.id JOIN users r ON t.receiver_id=r.id WHERE t.id=? AND t.receiver_id=? AND t.status='PENDING'";try(Connection c=Database.getConnection();PreparedStatement p=c.prepareStatement(q)){p.setInt(1,id);p.setInt(2,receiver);ResultSet r=p.executeQuery();return r.next()?map(r):null;}}
 public void received(int id)throws SQLException{try(Connection c=Database.getConnection();PreparedStatement p=c.prepareStatement("UPDATE transfers SET status='RECEIVED',received_at=NOW() WHERE id=?")){p.setInt(1,id);p.executeUpdate();}}
 public List<Transfer> list(int u,boolean sent)throws SQLException{String q="SELECT t.id,t.document_id,d.original_name,s.name,r.name,t.status,t.created_at,t.received_at FROM transfers t JOIN documents d ON t.document_id=d.id JOIN users s ON t.sender_id=s.id JOIN users r ON t.receiver_id=r.id WHERE t."+ (sent?"sender_id":"receiver_id")+"=? ORDER BY t.created_at DESC";List<Transfer>a=new ArrayList<>();try(Connection c=Database.getConnection();PreparedStatement p=c.prepareStatement(q)){p.setInt(1,u);ResultSet r=p.executeQuery();while(r.next())a.add(map(r));}return a;}
}
