const T=()=>localStorage.getItem("token");
async function api(u,o={}){o.headers={...(o.headers||{}),Authorization:"Bearer "+T()};let r=await fetch(u,o);let x=await r.json();if(r.status===401){localStorage.removeItem("token");location.href="login.html"}return x}
async function dash(){let m=await api("/api/me");user.textContent=m.name;let d=await api("/api/documents");dc.textContent=d.documents.length;docs.innerHTML=d.documents.map(x=>`<p><b>ID ${x.id}</b> — ${x.name} — ${x.size} bytes</p>`).join("")||"<p>No documents.</p>";let s=await api("/api/transfers/sent"),r=await api("/api/transfers/received");sc.textContent=s.transfers.length;rc.textContent=r.transfers.length}
if(document.getElementById("user"))dash();
if(document.getElementById("upload"))upload.onclick=async()=>{let f=file.files[0];if(!f){msg.textContent="Select a file";return}let b="----SH",a=new TextEncoder().encode(`--${b}\r\nContent-Disposition: form-data; name="file"; filename="${f.name}"\r\nContent-Type: application/octet-stream\r\n\r\n`),z=new TextEncoder().encode(`\r\n--${b}--\r\n`),raw=new Uint8Array(a.length+f.size+z.length);raw.set(a);raw.set(new Uint8Array(await f.arrayBuffer()),a.length);raw.set(z,a.length+f.size);let x=await api("/api/documents/upload",{method:"POST",headers:{"Content-Type":"multipart/form-data; boundary="+b,"X-File-Name":f.name},body:raw});msg.textContent=x.success?"Uploaded. Document ID: "+x.documentId:x.message};
if(document.getElementById("transfer"))transfer.onclick=async()=>{let x=await api("/api/transfers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({documentId:Number(documentId.value),receiverEmail:receiverEmail.value})});result.innerHTML=x.success?`<span class="success">Handover code: <b>${x.handoverCode}</b></span>`:`<span class="error">${x.message}</span>`};
if(document.getElementById("receive"))receive.onclick=async()=>{let x=await api("/api/transfers/receive",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({transferId:Number(transferId.value),handoverCode:code.value})});receiveResult.textContent=x.success?"Received: "+x.receivedFile:x.message};
async function history(){for(let [id,u] of [["sent","/api/transfers/sent"],["received","/api/transfers/received"]]){let x=await api(u);document.getElementById(id).innerHTML=x.transfers.map(t=>`<p>#${t.id} | ${t.document} | ${t.sender} → ${t.receiver} | <b>${t.status}</b></p>`).join("")||"<p>No transfers.</p>"}}
if(document.getElementById("sent"))history();
