CREATE DATABASE IF NOT EXISTS secure_handover;
USE secure_handover;
CREATE TABLE IF NOT EXISTS users(
 id INT PRIMARY KEY AUTO_INCREMENT,name VARCHAR(100) NOT NULL,email VARCHAR(190) UNIQUE NOT NULL,
 password_hash VARCHAR(255) NOT NULL,password_salt VARCHAR(255) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS documents(
 id INT PRIMARY KEY AUTO_INCREMENT,owner_id INT NOT NULL,original_name VARCHAR(255) NOT NULL,
 stored_name VARCHAR(255) UNIQUE NOT NULL,size_bytes BIGINT NOT NULL,uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(owner_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS transfers(
 id INT PRIMARY KEY AUTO_INCREMENT,document_id INT NOT NULL,sender_id INT NOT NULL,receiver_id INT NOT NULL,
 handover_code_hash VARCHAR(255) NOT NULL,status ENUM('PENDING','RECEIVED','CANCELLED') DEFAULT 'PENDING',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,received_at TIMESTAMP NULL,
 FOREIGN KEY(document_id) REFERENCES documents(id) ON DELETE CASCADE,
 FOREIGN KEY(sender_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY(receiver_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS audit_logs(
 id BIGINT PRIMARY KEY AUTO_INCREMENT,user_id INT NULL,action VARCHAR(100) NOT NULL,details VARCHAR(500),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS verification_records(
 id BIGINT PRIMARY KEY AUTO_INCREMENT,transfer_id INT NOT NULL,verification_hash VARCHAR(255) NOT NULL,
 verified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(transfer_id) REFERENCES transfers(id) ON DELETE CASCADE);
