package controller;
import com.sun.net.httpserver.*;import model.*;import service.*;import util.Json;import dao.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;
public class ApiHandler implements HttpHandler{
 private final AuthService auth=new AuthService();private final FileService files;private final TransferService transfers;
 public ApiHandler(FileService f){files=f;transfers=new TransferService(f);}
 public void handle(HttpExchange e)throws IOException{try{e.getResponseHeaders().set("Access-Control-Allow-Origin","*");e.getResponseHeaders().set("Access-Control-Allow-Headers","Content-Type,Authorization,X-File-Name");e.getResponseHeaders().set("Access-Control-Allow-Methods","GET,POST,OPTIONS");if(e.getRequestMethod().equals("OPTIONS")){e.sendResponseHeaders(204,-1);return;}String p=e.getRequestURI().getPath(),m=e.getRequestMethod();if(m.equals("POST")&&p.equals("/api/auth/register"))register(e);else if(m.equals("POST")&&p.equals("/api/auth/login"))login(e);else if(m.equals("POST")&&p.equals("/api/auth/logout"))logout(e);else if(m.equals("GET")&&p.equals("/api/me"))me(e);else if(m.equals("POST")&&p.equals("/api/documents/upload"))upload(e);else if(m.equals("GET")&&p.equals("/api/documents"))documents(e);else if(m.equals("POST")&&p.equals("/api/transfers"))create(e);else if(m.equals("GET")&&p.equals("/api/transfers/sent"))list(e,true);else if(m.equals("GET")&&p.equals("/api/transfers/received"))list(e,false);else if(m.equals("POST")&&p.equals("/api/transfers/receive"))receive(e);else send(e,404,Json.error("Endpoint not found"));}catch(Exception x){x.printStackTrace();send(e,400,Json.error(x.getMessage()==null?"Request failed":x.getMessage()));}}
 private int user(HttpExchange e){Integer i=auth.id(token(e));if(i==null)throw new IllegalArgumentException("Login required");return i;}
 private String token(HttpExchange e){String h=e.getRequestHeaders().getFirst("Authorization");return h!=null&&h.startsWith("Bearer ")?h.substring(7):null;}
 private String body(HttpExchange e)throws IOException{return new String(e.getRequestBody().readAllBytes(),StandardCharsets.UTF_8);}
 private void register(HttpExchange e)throws Exception{String j=body(e);int id=auth.register(Json.get(j,"name"),Json.get(j,"email"),Json.get(j,"password"));send(e,200,"{\"success\":true,\"userId\":"+id+"}");}
 private void login(HttpExchange e)throws Exception{String j=body(e);String t=auth.login(Json.get(j,"email"),Json.get(j,"password"));send(e,200,"{\"success\":true,\"token\":\""+Json.esc(t)+"\"}");}
 private void logout(HttpExchange e)throws Exception{auth.logout(token(e));send(e,200,"{\"success\":true}");}
 private void me(HttpExchange e)throws Exception{User u=auth.me(token(e));if(u==null){send(e,401,Json.error("Login required"));return;}send(e,200,"{\"success\":true,\"id\":"+u.id()+",\"name\":\""+Json.esc(u.name())+"\",\"email\":\""+Json.esc(u.email())+"\"}");}
 private void documents(HttpExchange e)throws Exception{int u=user(e);List<Document>a=new DocumentDao().all(u);StringBuilder s=new StringBuilder("{\"success\":true,\"documents\":[");for(int i=0;i<a.size();i++){Document d=a.get(i);if(i>0)s.append(',');s.append("{\"id\":").append(d.id()).append(",\"name\":\"").append(Json.esc(d.originalName())).append("\",\"size\":").append(d.sizeBytes()).append(",\"uploadedAt\":\"").append(Json.esc(d.uploadedAt())).append("\"}");}send(e,200,s.append("]}").toString());}
 private void create(HttpExchange e)throws Exception{int u=user(e);String j=body(e);Integer id=Json.integer(j,"documentId");String email=Json.get(j,"receiverEmail");if(id==null)throw new IllegalArgumentException("documentId required");String code=transfers.create(u,id,email);send(e,200,"{\"success\":true,\"handoverCode\":\""+code+"\"}");}
 private void receive(HttpExchange e)throws Exception{int u=user(e);String j=body(e);Integer id=Json.integer(j,"transferId");String code=Json.get(j,"handoverCode");if(id==null)throw new IllegalArgumentException("transferId required");String out=transfers.receive(u,id,code);send(e,200,"{\"success\":true,\"receivedFile\":\""+Json.esc(out)+"\"}");}
 private void list(HttpExchange e,boolean sent)throws Exception{int u=user(e);List<Transfer>a=sent?transfers.sent(u):transfers.received(u);StringBuilder s=new StringBuilder("{\"success\":true,\"transfers\":[");for(int i=0;i<a.size();i++){Transfer t=a.get(i);if(i>0)s.append(',');s.append("{\"id\":").append(t.id()).append(",\"document\":\"").append(Json.esc(t.documentName())).append("\",\"sender\":\"").append(Json.esc(t.senderName())).append("\",\"receiver\":\"").append(Json.esc(t.receiverName())).append("\",\"status\":\"").append(t.status()).append("\",\"createdAt\":\"").append(Json.esc(t.createdAt())).append("\"}");}send(e,200,s.append("]}").toString());}
 private void upload(HttpExchange e)throws Exception{int u=user(e);String ct=e.getRequestHeaders().getFirst("Content-Type");if(ct==null||!ct.contains("multipart/form-data"))throw new IllegalArgumentException("Use multipart/form-data");byte[] data=e.getRequestBody().readAllBytes();String b=ct.substring(ct.indexOf("boundary=")+9).replace("\"","");byte[] start=("--"+b+"\r\n").getBytes(StandardCharsets.ISO_8859_1);int a=index(data,start,0),h=index(data,new byte[]{13,10,13,10},a+start.length),n=index(data,("\r\n--"+b).getBytes(StandardCharsets.ISO_8859_1),h+4);if(a<0||h<0||n<0)throw new IOException("Invalid multipart request");byte[] file=Arrays.copyOfRange(data,h+4,n);String name=e.getRequestHeaders().getFirst("X-File-Name");Document d=files.upload(u,name==null?"file":name,file);send(e,200,"{\"success\":true,\"documentId\":"+d.id()+"}");}
 private static int index(byte[]a,byte[]b,int f){outer:for(int i=Math.max(0,f);i<=a.length-b.length;i++){for(int j=0;j<b.length;j++)if(a[i+j]!=b[j])continue outer;return i;}return -1;}
 private static void send(HttpExchange e,int status,String text)throws IOException{byte[]b=text.getBytes(StandardCharsets.UTF_8);e.getResponseHeaders().set("Content-Type","application/json");e.sendResponseHeaders(status,b.length);try(OutputStream o=e.getResponseBody()){o.write(b);}}
}
